networks:
  cluster_network:
    external: true
    name: cluster_network
services:
  client1:
    cap_add:
    - NET_ADMIN
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
        - node.hostname==ca66
      resources: &id001
        limits:
          cpus: '2'
          memory: 1G
        reservations:
          cpus: '1'
          memory: 512M
    environment:
    - POSTGRES_PASSWORD=password
    - POSTGRES_USER=postgres
    - POSTGRES_DB=postgres
    - NODE_ID=5
    image: edge_cluster:1
    networks:
      cluster_network:
        aliases:
        - client1
        ipv4_address: 172.20.1.6
  edge1:
    cap_add:
    - NET_ADMIN
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
        - node.hostname==ca66
      resources: *id001
    environment:
    - POSTGRES_PASSWORD=password
    - POSTGRES_USER=postgres
    - POSTGRES_DB=postgres
    - NODE_ID=1
    - CENTER_DELAY=50
    - EDGE_DELAYS=0,10,15,20
    - EDGE_IP=172.20.1.2
    - EDGE_PORT=50051
    image: edge_cluster:1
    networks:
      cluster_network:
        aliases:
        - edge1
        ipv4_address: 172.20.1.2
    volumes:
    - /root/TRCEDS:/root/TRCEDS
  edge2:
    cap_add:
    - NET_ADMIN
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
        - node.hostname==ca68
      resources: *id001
    environment:
    - POSTGRES_PASSWORD=password
    - POSTGRES_USER=postgres
    - POSTGRES_DB=postgres
    - NODE_ID=2
    - CENTER_DELAY=50
    - EDGE_DELAYS=10,0,15,20
    - EDGE_IP=172.20.1.3
    - EDGE_PORT=50051
    image: edge_cluster:1
    networks:
      cluster_network:
        aliases:
        - edge2
        ipv4_address: 172.20.1.3
    volumes:
    - /root/TRCEDS:/root/TRCEDS
  edge3:
    cap_add:
    - NET_ADMIN
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
        - node.hostname==ca96
      resources: *id001
    environment:
    - POSTGRES_PASSWORD=password
    - POSTGRES_USER=postgres
    - POSTGRES_DB=postgres
    - NODE_ID=3
    - CENTER_DELAY=50
    - EDGE_DELAYS=15,15,0,30
    - EDGE_IP=172.20.1.4
    - EDGE_PORT=50051
    image: edge_cluster:1
    networks:
      cluster_network:
        aliases:
        - edge3
        ipv4_address: 172.20.1.4
    volumes:
    - /root/TRCEDS:/root/TRCEDS
  edge4:
    cap_add:
    - NET_ADMIN
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
        - node.hostname==ca66
      resources: *id001
    environment:
    - POSTGRES_PASSWORD=password
    - POSTGRES_USER=postgres
    - POSTGRES_DB=postgres
    - NODE_ID=4
    - CENTER_DELAY=50
    - EDGE_DELAYS=20,20,30,0
    - EDGE_IP=172.20.1.5
    - EDGE_PORT=50051
    image: edge_cluster:1
    networks:
      cluster_network:
        aliases:
        - edge4
        ipv4_address: 172.20.1.5
    volumes:
    - /root/TRCEDS:/root/TRCEDS
version: '3.8'
