networks:
  cluster_network:
    attachable: true
    driver: overlay
    ipam:
      config:
      - subnet: 172.20.0.0/16
services:
  client1:
    cap_add:
    - NET_ADMIN
    deploy:
      placement:
        constraints:
        - node.hostname==ca96
      resources: *id001
    environment:
    - POSTGRES_PASSWORD=password
    - POSTGRES_USER=postgres
    - POSTGRES_DB=postgres
    - NODE_ID=5
    image: edge_cluster:1
    networks:
      cluster_network:
        ipv4_address: 172.20.1.6
    volumes:
      - /root/:/root/
  client2:
    cap_add:
    - NET_ADMIN
    deploy:
      placement:
        constraints:
        - node.hostname==ca96
      resources: *id001
    environment:
    - POSTGRES_PASSWORD=password
    - POSTGRES_USER=postgres
    - POSTGRES_DB=postgres
    - NODE_ID=6
    image: edge_cluster:1
    networks:
      cluster_network:
        ipv4_address: 172.20.1.7
    volumes:
      - /root/:/root/
  client3:
    cap_add:
    - NET_ADMIN
    deploy:
      placement:
        constraints:
        - node.hostname==ca96
      resources: *id001
    environment:
    - POSTGRES_PASSWORD=password
    - POSTGRES_USER=postgres
    - POSTGRES_DB=postgres
    - NODE_ID=7
    image: edge_cluster:1
    networks:
      cluster_network:
        ipv4_address: 172.20.1.8
    volumes:
      - /root/:/root/
  client4:
    cap_add:
    - NET_ADMIN
    deploy:
      placement:
        constraints:
        - node.hostname==ca96
      resources: *id001
    environment:
    - POSTGRES_PASSWORD=password
    - POSTGRES_USER=postgres
    - POSTGRES_DB=postgres
    - NODE_ID=8
    image: edge_cluster:1
    networks:
      cluster_network:
        ipv4_address: 172.20.1.9
    volumes:
      - /root/:/root/
  edge1:
    cap_add:
    - NET_ADMIN
    deploy:
      placement:
        constraints:
        - node.hostname==ca66
      resources: *id001
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - NODE_ID=1
      - CENTER_DELAY=50
      - EDGE_DELAYS=0,10,15,20
      - EDGE_IP=172.20.1.2  # 新增
      - EDGE_PORT=50051     # 新增
    command: /root//build/edge_server $EDGE_IP $EDGE_PORT /root//config/config.json

  edge2:
    cap_add:
    - NET_ADMIN
    deploy:
      placement:
        constraints:
        - node.hostname==ca66
      resources: *id001
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - NODE_ID=2
      - CENTER_DELAY=50
      - EDGE_DELAYS=10,0,15,20
      - EDGE_IP=172.20.1.3  # 新增
      - EDGE_PORT=50051     # 新增
    command: /root//build/edge_server $EDGE_IP $EDGE_PORT /root//config/config.json

  edge3:
    cap_add:
    - NET_ADMIN
    deploy:
      placement:
        constraints:
        - node.hostname==ca66
      resources: *id001
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - NODE_ID=3
      - CENTER_DELAY=50
      - EDGE_DELAYS=15,15,0,30
      - EDGE_IP=172.20.1.4  # 新增
      - EDGE_PORT=50051     # 新增
    command: /root//build/edge_server $EDGE_IP $EDGE_PORT /root//config/config.json

  edge4:
    cap_add:
    - NET_ADMIN
    deploy:
      placement:
        constraints:
        - node.hostname==ca66
      resources: *id001
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - NODE_ID=4
      - CENTER_DELAY=50
      - EDGE_DELAYS=20,20,30,0
      - EDGE_IP=172.20.1.5  # 新增
      - EDGE_PORT=50051     # 新增
    command: /root//build/edge_server $EDGE_IP $EDGE_PORT /root//config/config.json
version: '3.8'
